# Homebrew formula template for funcspec.
#
# The live formula is in the tap repo (https://github.com/narbs/homebrew-funcspec)
# and is regenerated by the `homebrew` job in .github/workflows/release.yml on
# every non-prerelease tag — version and SHA256 placeholders below are filled
# in from the published release's checksums.sha256 file.
#
# Users install via:  brew install narbs/funcspec/funcspec
class Funcspec < Formula
  desc "Command-line interface for FuncSpec"
  homepage "https://funcspec.net"
  version "0.2.22" # replaced by release workflow
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-apple-darwin.zip"
      sha256 "f45189292ffe026373ebfc4d0ba3d77c464a95204ceda1ec449e5d70b100f319"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-apple-darwin.zip"
      sha256 "2f74b3280c17ab4e4c56ff889af532164d32407594dfc38ec4f28e3dadf4caa6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "495f8869646f4d14404643c4bf3405f7367770eadfb3a7e2906e56ccbb988d71"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3884bff8d7453445a82cd31935c5f70b83415fb195fe7b44bf5601b86487e262"
    end
  end

  def install
    bin.install "funcspec"
  end

  def caveats
    <<~EOS
      funcspec has been installed. Run `funcspec login` to authenticate with funcspec.net.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funcspec --version")
  end
end
