# Homebrew formula template for funcspec.
#
# The live formula is in the tap repo (https://github.com/narbs/homebrew-funcspec)
# and is regenerated by the `homebrew` job in .github/workflows/release.yml on
# every non-prerelease tag — version and SHA256 placeholders below are filled
# in from the published release's checksums.sha256 file.
#
# Users install via:  brew install narbs/funcspec/funcspec
class Funcspec < Formula
  desc "Command-line interface for FuncSpec"
  homepage "https://funcspec.net"
  version "0.2.21" # replaced by release workflow
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-apple-darwin.zip"
      sha256 "167e33c055f04cdd16901211705c897f45b9eedb258afd640f87dbdff50e7bcb"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-apple-darwin.zip"
      sha256 "be1524632dec7b50d12316c9dedb64f97b1a15ee33aeea46169ddf57c1b9f1f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "328486622c8ae52e67f065a39a5bec4fb7983ed6ac628f9d8586843029a33823"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c2e0882269ea539967f2a8431cc12ed8d856f3b9520a137282b12657c7b3a892"
    end
  end

  def install
    bin.install "funcspec"
  end

  def caveats
    <<~EOS
      funcspec has been installed. Run `funcspec login` to authenticate with funcspec.net.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funcspec --version")
  end
end
