# Homebrew formula template for funcspec.
#
# The live formula is in the tap repo (https://github.com/narbs/homebrew-funcspec)
# and is regenerated by the `homebrew` job in .github/workflows/release.yml on
# every non-prerelease tag — version and SHA256 placeholders below are filled
# in from the published release's checksums.sha256 file.
#
# Users install via:  brew install narbs/funcspec/funcspec
class Funcspec < Formula
  desc "Command-line interface for FuncSpec"
  homepage "https://funcspec.net"
  version "0.2.23" # replaced by release workflow
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-apple-darwin.zip"
      sha256 "eb58ca7df9b06e53d1dd606b86be978d99b3d77299d94a5645659258446ae9a2"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-apple-darwin.zip"
      sha256 "b8996d206d643229d5f74829e0ce0dc3a5c6fb92cfebfaa67c71023854d306fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "97047925c137f77bf400c0922a6a10078f15049b7c7a3d49720bd19684487da4"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "7989f66df8b8da19b60b3e5e1a528f075de4b020c2638b7769689aecdeb6432d"
    end
  end

  def install
    bin.install "funcspec"
  end

  def caveats
    <<~EOS
      funcspec has been installed. Run `funcspec login` to authenticate with funcspec.net.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funcspec --version")
  end
end
